name: mc-publish
on:
  workflow_dispatch:
  push:
    branches:
      - 1.16.5

jobs:
  build:
    # ...
    permissions:
      contents: write
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: Kira-NT/mc-publish@v3.3.0
        with:
          # Only include this section if you wish to publish
          # your assets on Modrinth.
          modrinth-id: e1Ub5iPm
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          # Only include this section if you wish to publish
          # your assets on CurseForge.
          curseforge-id: 676140
          curseforge-token: ${{ secrets.CURSE_TOKEN }}

          changelog-file: changelog.md
